version: "3"

networks:
  proxy-net:
    external: true

volumes:
  home:

services:
  webtop:
    # image: lscr.io/linuxserver/webtop:latest
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - CUSTOM_USER=l
      - PASSWORD=l
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - home:/config
      # - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 4100:3000
      - 4101:3001
    shm_size: "1gb"
    restart: unless-stopped